version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - stbrody
  assignees:
  - stbrody
  allow:
  - dependency-type: production
