FROM node:16

WORKDIR /js-ceramic

COPY package.json package-lock.json lerna.json tsconfig.json ./
RUN npm install

COPY packages ./packages

RUN npx lerna bootstrap --hoist

COPY types ./types

RUN npm run build

EXPOSE 7007

ENTRYPOINT ["./packages/cli/bin/ceramic.js", "daemon"]
