/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    { type: 'doc', id: 'introduction', label: 'Introduction' },
    {
      type: 'category',
      collapsed: false,
      label: 'Getting Started',
      items: ['installation'],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Guides',
      link: { type: 'generated-index' },
      items: [
        { type: 'doc', id: 'guides/running-dev-node/introduction', label: 'Running Development Nodes' },
        { type: 'doc', id: 'guides/running-prod-node/introduction', label: 'Running Production Nodes' },
      ],
    },
  ],
  api: [
    {
      type: 'category',
      collapsed: false,
      label: 'Modules',
      items: [
        { type: 'doc', id: 'api/modules/cli', label: 'CLI' },
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'APIs',
      items: [
        { type: 'doc', id: 'api/index', label: 'Overview' },
        {
          type: 'category',
          collapsed: false,
          label: 'ENUMs',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'api/enums'},
          ],
        },
        {
          type: 'category',
          collapsed: false,
          label: 'Classes',
          link: { type: 'generated-index' },
          items: [
            {type: 'autogenerated', dirName: 'api/classes'},
          ],
        },
      ],
    },
  ],
};

module.exports = sidebars;
