name: Trigger CircleCI tests

on:
  push: # all push events
  workflow_dispatch: # manually triggered

jobs:
  circleci:
    name: Trigger CircleCI tests
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'ukstv' }}
    steps:
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        with:
          GHA_Actor: "smrz2001"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
