name: Trigger CircleCI tests

on:
  push:
  workflow_dispatch: # manually triggered

jobs:
  circleci:
    name: Trigger CircleCI tests
    runs-on: ubuntu-latest
    steps:
      - uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
          GHA_Actor: "smrz2001"
