name: Publish npm packages

on:
  push:
    branches: [ feat/npm_publish ]
  workflow_dispatch:
    inputs:
      type:
        description: 'Type of publish (one of: rc, full)'
        required: true
        default: 'rc'
      dryrun:
        description: 'Dry run or actual publish (one of: true, false)'
        required: true
        default: 'true'

jobs:
  publish:
    runs-on: self-hosted
    steps:
      -
        name: Setup environment
        id: set-vars
        run: |
          if [[ "${{ github.event.inputs.type }}" == "full" ]]; then
            echo "::set-output name=target-branch::master"
            echo "::set-output name=source-branch::release-candidate"
            echo "::set-output name=tag::latest"
          else
            # Default to `release-candidate`
            echo "::set-output name=target-branch::release-candidate"
            echo "::set-output name=source-branch::develop"
            echo "::set-output name=tag::release-candidate"
          fi
          # If it's not explicitly `true`, it's `false`
          echo "::set-output name=dry-run::${{ github.event.inputs.dryrun }} == 'true')"
      -
        name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.set-vars.outputs.target-branch }}
      -
        name: Merge ${{ steps.set-vars.outputs.source-branch }} -> ${{ steps.set-vars.outputs.target-branch }}
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ steps.set-vars.outputs.source-branch }}
          target_branch: ${{ steps.set-vars.outputs.target-branch }}
#          github_token: ${{ github.token }}
      -
        name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      -
        name: Initialize and build code
        run: npm ci --ignore-scripts && npm run build --if-present
      -
        name: Publish packages to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          TAG: ${{ steps.set-vars.outputs.tag }}
          DRY_RUN: ${{ steps.set-vars.outputs.dry-run }}
        run: |
          DRY_RUN_CMD=""
          if [[ "$DRY_RUN" == "true"]]; then
            DRY_RUN_CMD="--dry-run"
          fi
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish:$TAG --ignore-scripts $DRY_RUN_CMD
      -
        name: Update and push code to ${{ steps.set-vars.outputs.source-branch }}
        if: ${{ steps.set-vars.outputs.dry-run == 'false' }}
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ steps.set-vars.outputs.target-branch }}
          target_branch: ${{ steps.set-vars.outputs.source-branch }}
          github_token: ${{ github.token }}
      -
        # Always merge and push to `develop` - if it's already been merged to above, this action will have no effect
        name: Update and push code to ${{ steps.set-vars.outputs.source-branch }}
        if: ${{ steps.set-vars.outputs.dry-run == 'false' }}
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: ${{ steps.set-vars.outputs.target-branch }}
          target_branch: develop
          github_token: ${{ github.token }}
