name: Publish npm release/RC (reusable)

on:
  workflow_call:

jobs:
  publish_main:
    name: Publish release
    uses: ./.github/workflows/reusable-release.yml
    with:
      release_type: main
    secrets: inherit

  publish_rc:
    name: Publish RC
    needs: publish_main
    uses: ./.github/workflows/reusable-release.yml
    with:
      release_type: rc
    secrets: inherit
