name: Publish npm release/RC (reusable)

on:
  workflow_call:

jobs:
  publish_main:
    uses: ./.github/workflows/reusable-release.yml
    with:
      release_type: main
    secrets: inherit

  publish_rc:
    needs: publish_main
    uses: ./.github/workflows/reusable-release.yml
    with:
      release_type: rc
    secrets: inherit
